version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=dbinsta-weblight.c9etmdnthkjs.ap-south-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=admin123
    ports: 
      - '8090:8090' 
